<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\Applicant;

class ApplicantSeeder extends Seeder
{
    public function run()
    {
        // Check if data already exists
        $applicantModel = new Applicant();
        $count = $applicantModel->countAllResults();
        
        if ($count > 0) {
            echo "Applicant data already seeded, skipping...\n";
            return;
        }

        $data = [
            // Draft applicant (user_id = 4 - john_doe)
            [
                'user_id' => 4,
                'nis' => '0012345678',
                'nik' => '1234567890123456',
                'nama_lengkap' => 'John Doe',
                'nama_panggilan' => 'John',
                'jenis_kelamin' => 'laki-laki',
                'tanggal_lahir' => '2007-05-15',
                'tempat_lahir' => 'Jakarta',
                'agama' => 'Islam',
                'status_keluarga' => 'anak_kandung',
                'anak_ke' => 1,
                'jumlah_saudara' => 2,
                'alamat_jalan' => 'Jl. Merdeka No. 123',
                'dusun' => 'Dusun A',
                'kelurahan' => 'Kelurahan A',
                'kecamatan' => 'Kecamatan Jakarta Pusat',
                'kabupaten' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12345',
                'nomor_telepon' => '0212345678',
                'nomor_hp' => '08123456789',
                'asal_sekolah' => 'SMP Negeri 1 Jakarta',
                'npsn_sekolah_asal' => '20123456',
                'nilai_rata_rata' => '8.50',
                'nilai_un_indo' => '8.75',
                'nilai_un_math' => '8.50',
                'nilai_un_english' => '8.25',
                'nilai_un_science' => '8.60',
                'nama_ayah' => 'Ahmad Doe',
                'nik_ayah' => '1234567890123456',
                'pendidikan_ayah' => 'S1',
                'pekerjaan_ayah' => 'Pegawai Negeri Sipil',
                'penghasilan_ayah' => '> 5jt',
                'nomor_hp_ayah' => '08123456789',
                'nama_ibu' => 'Siti Doe',
                'nik_ibu' => '1234567890123457',
                'pendidikan_ibu' => 'S1',
                'pekerjaan_ibu' => 'Guru',
                'penghasilan_ibu' => '2jt-5jt',
                'nomor_hp_ibu' => '08123456788',
                'prestasi_akademik' => 'Juara 2 Olimpiade Matematika',
                'prestasi_non_akademik' => 'Paskibra, Debat Bahasa Inggris',
                'nomor_pendaftaran' => 'PPDB-202512-0001',
                'status' => 'draft',
                'dokumen_upload' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Submitted applicant (user_id = 5 - jane_smith)
            [
                'user_id' => 5,
                'nis' => '0022345678',
                'nik' => '2234567890123456',
                'nama_lengkap' => 'Jane Smith',
                'nama_panggilan' => 'Jane',
                'jenis_kelamin' => 'perempuan',
                'tanggal_lahir' => '2007-08-20',
                'tempat_lahir' => 'Bandung',
                'agama' => 'Kristen',
                'status_keluarga' => 'anak_kandung',
                'anak_ke' => 2,
                'jumlah_saudara' => 1,
                'alamat_jalan' => 'Jl. Sudirman No. 456',
                'dusun' => 'Dusun B',
                'kelurahan' => 'Kelurahan B',
                'kecamatan' => 'Kecamatan Bandung Pusat',
                'kabupaten' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40123',
                'nomor_telepon' => '0222345678',
                'nomor_hp' => '08223456789',
                'asal_sekolah' => 'SMP Negeri 2 Bandung',
                'npsn_sekolah_asal' => '20223456',
                'nilai_rata_rata' => '8.75',
                'nilai_un_indo' => '9.00',
                'nilai_un_math' => '8.75',
                'nilai_un_english' => '8.50',
                'nilai_un_science' => '8.75',
                'nama_ayah' => 'Robert Smith',
                'nik_ayah' => '2234567890123456',
                'pendidikan_ayah' => 'S1',
                'pekerjaan_ayah' => 'Direktur',
                'penghasilan_ayah' => '> 5jt',
                'nomor_hp_ayah' => '08223456789',
                'nama_ibu' => 'Linda Smith',
                'nik_ibu' => '2234567890123457',
                'pendidikan_ibu' => 'S2',
                'pekerjaan_ibu' => 'Dosen',
                'penghasilan_ibu' => '2jt-5jt',
                'nomor_hp_ibu' => '08223456788',
                'prestasi_akademik' => 'Juara 1 Kompetisi Sains',
                'prestasi_non_akademik' => 'Anggota Paduan Suara',
                'nomor_pendaftaran' => 'PPDB-202512-0002',
                'status' => 'submitted',
                'tanggal_submit' => date('Y-m-d H:i:s'),
                'dokumen_upload' => 1,
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Verified applicant
            [
                'user_id' => 6,
                'nis' => '0032345678',
                'nik' => '3234567890123456',
                'nama_lengkap' => 'Michael Johnson',
                'nama_panggilan' => 'Mike',
                'jenis_kelamin' => 'laki-laki',
                'tanggal_lahir' => '2007-03-10',
                'tempat_lahir' => 'Surabaya',
                'agama' => 'Islam',
                'status_keluarga' => 'anak_kandung',
                'anak_ke' => 1,
                'jumlah_saudara' => 2,
                'alamat_jalan' => 'Jl. Ahmad Yani No. 789',
                'dusun' => 'Dusun C',
                'kelurahan' => 'Kelurahan C',
                'kecamatan' => 'Kecamatan Surabaya Pusat',
                'kabupaten' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60123',
                'nomor_telepon' => '0313345678',
                'nomor_hp' => '08333456789',
                'asal_sekolah' => 'SMP Negeri 3 Surabaya',
                'npsn_sekolah_asal' => '20333456',
                'nilai_rata_rata' => '8.80',
                'nilai_un_indo' => '8.90',
                'nilai_un_math' => '8.85',
                'nilai_un_english' => '8.60',
                'nilai_un_science' => '8.90',
                'nama_ayah' => 'David Johnson',
                'nik_ayah' => '3234567890123456',
                'pendidikan_ayah' => 'Diploma',
                'pekerjaan_ayah' => 'Pengusaha',
                'penghasilan_ayah' => '> 5jt',
                'nomor_hp_ayah' => '08333456789',
                'nama_ibu' => 'Mary Johnson',
                'nik_ibu' => '3234567890123457',
                'pendidikan_ibu' => 'S1',
                'pekerjaan_ibu' => 'Dokter',
                'penghasilan_ibu' => '> 5jt',
                'nomor_hp_ibu' => '08333456788',
                'prestasi_akademik' => 'Juara Kompetisi Programming',
                'prestasi_non_akademik' => 'Kapten Basket',
                'nomor_pendaftaran' => 'PPDB-202512-0003',
                'status' => 'verified',
                'tanggal_submit' => date('Y-m-d H:i:s', strtotime('-7 days')),
                'dokumen_upload' => 1,
                'catatan_verifikasi' => 'Semua dokumen lengkap dan valid',
                'created_at' => date('Y-m-d H:i:s', strtotime('-10 days')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-5 days')),
            ],
            // Accepted applicant
            [
                'user_id' => 7,
                'nis' => '0042345678',
                'nik' => '4234567890123456',
                'nama_lengkap' => 'Sarah Williams',
                'nama_panggilan' => 'Sarah',
                'jenis_kelamin' => 'perempuan',
                'tanggal_lahir' => '2007-06-25',
                'tempat_lahir' => 'Yogyakarta',
                'agama' => 'Islam',
                'status_keluarga' => 'anak_kandung',
                'anak_ke' => 1,
                'jumlah_saudara' => 0,
                'alamat_jalan' => 'Jl. Kaliurang No. 321',
                'dusun' => 'Dusun D',
                'kelurahan' => 'Kelurahan D',
                'kecamatan' => 'Kecamatan Yogyakarta',
                'kabupaten' => 'Yogyakarta',
                'provinsi' => 'DI Yogyakarta',
                'kode_pos' => '55123',
                'nomor_telepon' => '0274345678',
                'nomor_hp' => '08274456789',
                'asal_sekolah' => 'SMP Negeri 4 Yogyakarta',
                'npsn_sekolah_asal' => '20274456',
                'nilai_rata_rata' => '8.90',
                'nilai_un_indo' => '9.00',
                'nilai_un_math' => '8.90',
                'nilai_un_english' => '8.80',
                'nilai_un_science' => '8.95',
                'nama_ayah' => 'William Williams',
                'nik_ayah' => '4234567890123456',
                'pendidikan_ayah' => 'S2',
                'pekerjaan_ayah' => 'Professor',
                'penghasilan_ayah' => '> 5jt',
                'nomor_hp_ayah' => '08274456789',
                'nama_ibu' => 'Elizabeth Williams',
                'nik_ibu' => '4234567890123457',
                'pendidikan_ibu' => 'S2',
                'pekerjaan_ibu' => 'Peneliti',
                'penghasilan_ibu' => '> 5jt',
                'nomor_hp_ibu' => '08274456788',
                'prestasi_akademik' => 'Juara 1 Science Fair Nasional',
                'prestasi_non_akademik' => 'Model UN, Debat Inggris',
                'nomor_pendaftaran' => 'PPDB-202512-0004',
                'status' => 'diterima',
                'tanggal_submit' => date('Y-m-d H:i:s', strtotime('-15 days')),
                'dokumen_upload' => 1,
                'catatan_verifikasi' => 'Lulus seleksi akademik dan wawancara',
                'created_at' => date('Y-m-d H:i:s', strtotime('-20 days')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-8 days')),
            ],
            // Rejected applicant
            [
                'user_id' => 8,
                'nis' => '0052345678',
                'nik' => '5234567890123456',
                'nama_lengkap' => 'Thomas Brown',
                'nama_panggilan' => 'Tom',
                'jenis_kelamin' => 'laki-laki',
                'tanggal_lahir' => '2007-09-12',
                'tempat_lahir' => 'Medan',
                'agama' => 'Kristen',
                'status_keluarga' => 'anak_kandung',
                'anak_ke' => 2,
                'jumlah_saudara' => 1,
                'alamat_jalan' => 'Jl. Gatot Subroto No. 654',
                'dusun' => 'Dusun E',
                'kelurahan' => 'Kelurahan E',
                'kecamatan' => 'Kecamatan Medan',
                'kabupaten' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'kode_pos' => '20123',
                'nomor_telepon' => '0612345678',
                'nomor_hp' => '08612456789',
                'asal_sekolah' => 'SMP Negeri 5 Medan',
                'npsn_sekolah_asal' => '20612456',
                'nilai_rata_rata' => '7.20',
                'nilai_un_indo' => '7.00',
                'nilai_un_math' => '7.10',
                'nilai_un_english' => '7.30',
                'nilai_un_science' => '7.40',
                'nama_ayah' => 'Charles Brown',
                'nik_ayah' => '5234567890123456',
                'pendidikan_ayah' => 'SMA',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'penghasilan_ayah' => '1jt-2jt',
                'nomor_hp_ayah' => '08612456789',
                'nama_ibu' => 'Patricia Brown',
                'nik_ibu' => '5234567890123457',
                'pendidikan_ibu' => 'SMP',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'penghasilan_ibu' => '< 500rb',
                'nomor_hp_ibu' => '08612456788',
                'prestasi_akademik' => 'Tidak ada prestasi',
                'nomor_pendaftaran' => 'PPDB-202512-0005',
                'status' => 'ditolak',
                'tanggal_submit' => date('Y-m-d H:i:s', strtotime('-12 days')),
                'dokumen_upload' => 1,
                'catatan_verifikasi' => 'Nilai akademik di bawah standar penerimaan',
                'created_at' => date('Y-m-d H:i:s', strtotime('-18 days')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-6 days')),
            ],
        ];

        $applicantModel = new Applicant();
        foreach ($data as $record) {
            $applicantModel->insert($record);
        }
        
        echo "✓ " . count($data) . " applicant records seeded successfully!\n";
        echo "  - 1 Draft\n";
        echo "  - 1 Submitted\n";
        echo "  - 1 Verified\n";
        echo "  - 1 Accepted (Diterima)\n";
        echo "  - 1 Rejected (Ditolak)\n";
    }
}
